image: hhucn/python

stages:
  - test

before_script:
  - export PIP_CACHE_DIR="pip-cache"
  - pip install --quiet -U pip

# ------------------------------------------------------------------------------
# Job definitions

flake8:
  stage: test
  script:
    - pip3 install --quiet flake8
    - flake8 .
  allow_failure: true

unittests:
  stage: test
  script:
    - pip install --quiet -r requirements.txt
    - nosetests --with-coverage dabasco dabasco/adf dabasco/af dabasco/aspic dabasco/doj
  coverage: '/^TOTAL\s*\d+\s*\d+\s*(\d+\%)\s*$/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 10 mins

