
# DABASCO API: output constants
DUMMY_LITERAL_NAME_OPINION = 'opinion_dummy'
DUMMY_LITERAL_NAME_ASSUMPTIONS = 'assumptions_dummy'

LITERAL_PREFIX_OPINION_ASSUME = 'ua'
LITERAL_PREFIX_OPINION_REJECT = 'ur'
LITERAL_PREFIX_ASSUMPTION_ASSUME = 'a'
LITERAL_PREFIX_ASSUMPTION_REJECT = 'r'
LITERAL_PREFIX_INFERENCE_RULE = 'i'
LITERAL_PREFIX_NOT = 'n'

# DABASCO API: input constants
KEYWORD_OPINION_WEAK = 'weak'
KEYWORD_OPINION_STRONG = 'strong'
KEYWORD_OPINION_STRICT = 'strict'

# TOAST API: interface keywords
TOAST_SYMBOL_RULE_DEFEASIBLE = '=>'
TOAST_SYMBOL_RULE_STRICT = '->'
TOAST_SYMBOL_NEGATION = '~'
TOAST_SYMBOL_PREFERENCE = '<'
TOAST_SYMBOL_RULE_NAME_PREFIX = '['
TOAST_SYMBOL_RULE_NAME_SUFFIX = ']'

TOAST_KEYWORD_ASSUMPTIONS = 'assumptions'
TOAST_KEYWORD_AXIOMS = 'axioms'
TOAST_KEYWORD_RULES = 'rules'
TOAST_KEYWORD_RULEPREFS = 'rulePrefs'
TOAST_KEYWORD_LITERALPREFS = 'kbPrefs'
TOAST_KEYWORD_LINK_PRINCIPLE = 'link'
TOAST_KEYWORD_CONTRARINESS = 'contrariness'
TOAST_KEYWORD_SEMANTICS = 'semantics'

TOAST_KEYWORD_LAST_LINK_PRINCIPLE = 'last'
TOAST_KEYWORD_WEAKEST_LINK_PRINCIPLE = 'weakest'
