
# DABASCO API: output constants
DUMMY_LITERAL_NAME_OPINION = 'opinion_dummy'
DUMMY_LITERAL_NAME_ASSUMPTIONS = 'assumptions_dummy'

LITERAL_PREFIX_OPINION_ASSUME = 'ua'
LITERAL_PREFIX_OPINION_REJECT = 'ur'
LITERAL_PREFIX_ASSUMPTION_ASSUME = 'a'
LITERAL_PREFIX_ASSUMPTION_REJECT = 'r'
LITERAL_PREFIX_INFERENCE_RULE = 'i'
LITERAL_PREFIX_NOT = 'n'

# DABASCO API: input constants
KEYWORD_OPINION_WEAK = 'weak'
KEYWORD_OPINION_STRONG = 'strong'
KEYWORD_OPINION_STRICT = 'strict'

# DBAS API: interface keywords
DBAS_KEYWORD_ACCEPTED_STATEMENTS_EXPLICIT = 'marked_statements'
DBAS_KEYWORD_ACCEPTED_STATEMENTS_IMPLICIT = 'accepted_statements_via_click'
DBAS_KEYWORD_REJECTED_STATEMENTS_IMPLICIT = 'rejected_statements_via_click'
DBAS_KEYWORD_ACCEPTED_ARGUMENTS_EXPLICIT = 'marked_arguments'
DBAS_KEYWORD_REJECTED_ARGUMENTS_EXPLICIT = 'rejected_arguments'

DBAS_KEYWORD_STATEMENTS = 'nodes'
DBAS_KEYWORD_INFERENCE_RULES = 'inferences'
DBAS_KEYWORD_INFERENCE_RULE_ID = 'id'
DBAS_KEYWORD_INFERENCE_RULE_PREMISES = 'premises'
DBAS_KEYWORD_INFERENCE_RULE_CONCLUSION = 'conclusion'
DBAS_KEYWORD_INFERENCE_RULE_SUPPORTIVE = 'is_supportive'
DBAS_KEYWORD_UNDERCUTS = 'undercuts'
DBAS_KEYWORD_UNDERCUT_ID = 'id'
DBAS_KEYWORD_UNDERCUT_PREMISES = 'premises'
DBAS_KEYWORD_UNDERCUT_CONCLUSION = 'conclusion'

# TOAST API: interface keywords
TOAST_SYMBOL_RULE_DEFEASIBLE = '=>'
TOAST_SYMBOL_RULE_STRICT = '->'
TOAST_SYMBOL_NEGATION = '~'
TOAST_SYMBOL_PREFERENCE = '<'
TOAST_SYMBOL_RULE_NAME_PREFIX = '['
TOAST_SYMBOL_RULE_NAME_SUFFIX = ']'

TOAST_KEYWORD_ASSUMPTIONS = 'assumptions'
TOAST_KEYWORD_AXIOMS = 'axioms'
TOAST_KEYWORD_RULES = 'rules'
TOAST_KEYWORD_RULEPREFS = 'rulePrefs'
TOAST_KEYWORD_LITERALPREFS = 'kbPrefs'
TOAST_KEYWORD_LINK_PRINCIPLE = 'link'
TOAST_KEYWORD_CONTRARINESS = 'contrariness'
TOAST_KEYWORD_SEMANTICS = 'semantics'

TOAST_KEYWORD_LAST_LINK_PRINCIPLE = 'last'
TOAST_KEYWORD_WEAKEST_LINK_PRINCIPLE = 'weakest'
